var CADApp = CADApp || {};
CADApp.state = {
    currentTool: 'select',
    activeCommand: null,
    firstPoint: null,
    currentPolylinePoints: [],
    currentPolylineSegmentIds: [],
    isDragging: false,
    modificationTarget: null,
    dimensionTarget: null,
    startX: 0, startY: 0,
    mouseX: 0, mouseY: 0,
    shapes: [],
    tempShape: null,
    selectedShape: null,
    snapTolerance: 10,
    shapeIdCounter: 1,
    isShiftPressed: false,
    history: [[]],
    historyIndex: 0,
    lastClickTime: 0,
    lastClickShape: null,
    editingDimension: null,
};
